# Generated by Django 5.1.1 on 2024-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="can_preview",
            field=models.BooleanField(
                default=False, help_text="If user doesn't have access"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("publish", "Published"),
                    ("soon", "Coming Soon"),
                    ("draft", "Draft"),
                ],
                default="publish",
                max_length=10,
            ),
        ),
    ]
