# Generated by Django 5.1.1 on 2024-09-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0008_alter_lesson_options_course_timestamp_course_updated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=130, null=True
            ),
        ),
    ]
