# Generated by Django 5.1.1 on 2024-10-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_course_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=130, null=True
            ),
        ),
    ]
