# Generated by Django 5.1.1 on 2024-10-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
